# Generated by Django 3.2.4 on 2021-06-19 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_remove_food_garnish'),
        ('main', '0002_alter_choice_garnish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='garnish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.garnish'),
        ),
    ]
