# Generated by Django 3.2.4 on 2021-06-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garnish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images', verbose_name='food image'),
        ),
        migrations.AddField(
            model_name='food',
            name='garnish',
            field=models.ManyToManyField(blank=True, null=True, to='food.Garnish'),
        ),
    ]
