# Generated by Django 3.2.4 on 2021-06-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210619_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='garnish',
            field=models.ManyToManyField(blank=True, to='food.Garnish'),
        ),
    ]
