# Generated by Django 3.2.4 on 2021-06-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_remove_food_garnish'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='needs_garnish',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
