# Generated by Django 3.2.4 on 2021-06-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
