# Generated by Django 3.2.4 on 2021-06-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods_app', '0002_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='food image'),
        ),
    ]
