# Generated by Django 3.2.4 on 2021-06-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods_app', '0005_alter_food_garnish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='garnish',
        ),
    ]
